name: GitHub Actions Demo

on:
  push:
    branches:
      - main
jobs:
  hugo-compile:
    runs-on: ubuntu-latest
    steps:
      run: |
          apt-get update -y
          wget https://github.com/gohugoio/hugo/releases/download/v0.79.0/hugo_0.79.0_Linux-64bit.deb
          dpkg -i hugo_0.79.0_Linux-64bit.deb
          hugo versionls -ltr
