name: GitHub Actions Demo

on:
  push:
    branches:
      - main
jobs:
  hugo-install:
    runs-on: ubuntu-latest
    steps:
      - name: Install Hugo
        run: |
            apt-get update -y
            wget https://github.com/gohugoio/hugo/releases/download/v0.79.0/hugo_0.79.0_Linux-64bit.deb
            dpkg -i hugo_0.79.0_Linux-64bit.deb
            hugo versionls -ltr
